repository:
  default_branch: develop
  delete_branch_on_merge: true

branches:
  - name: main
    protection:
      required_status_checks:
        strict: true
        contexts:
          - CI
      required_pull_request_reviews:
        required_approving_review_count: 1
      enforce_admins: true
  - name: develop
    protection:
      required_status_checks:
        strict: true
        contexts:
          - CI
      required_pull_request_reviews:
        required_approving_review_count: 1
      enforce_admins: true
